-- students
CREATE TABLE IF NOT EXISTS students (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR(50)  NOT NULL,
  furigana    VARCHAR(50),
  nickname    VARCHAR(50),
  email       VARCHAR(100) NOT NULL,
  region      VARCHAR(50),
  age         INT,
  gender      VARCHAR(30),
  remark      VARCHAR(1000),
  is_deleted  BOOLEAN DEFAULT FALSE
);

-- courses
CREATE TABLE IF NOT EXISTS courses (
  course_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name  VARCHAR(30) NOT NULL UNIQUE
);

-- students_courses
CREATE TABLE IF NOT EXISTS students_courses (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id  INT,
  course_id   INT NOT NULL,
  start_date  TIMESTAMP NOT NULL,
  end_date    TIMESTAMP,
  CONSTRAINT fk_student_id FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_sc_course  FOREIGN KEY (course_id)  REFERENCES courses(course_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);